{% set name = "pytest-subprocess" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-subprocess-{{ version }}.tar.gz
  sha256: d7693b96f588f39b84c7b2b5c04287459246dfae6be1dd4098937a728ad4fbe3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytest >=4.0.0

test:
  imports:
    - pytest_subprocess
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/pytest-subprocess/
  summary: A plugin to fake subprocess for pytest
  dev_url: https://github.com/aklajnert/pytest-subprocess
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aklajnert
    - henryiii
